In [7]:
import os
import json
from copy import copy, deepcopy
import torch
import numpy as np

In [2]:
mpqa2_docids = open("/workspace/opinion/data/30-mpqa/database.mpqa.2.0/doclist.attitudeSubset").read().splitlines()

dev_docids = open("/workspace/opinion/baselines/02-naacl-mpqa-srl4orl/datasplit/new/filelist_dev").read().splitlines()
test_docids = open("/workspace/opinion/baselines/02-naacl-mpqa-srl4orl/datasplit/new/filelist_test0").read().splitlines()
train_docids = open("/workspace/opinion/baselines/02-naacl-mpqa-srl4orl/datasplit/new/filelist_train0").read().splitlines()

In [3]:
print(len(mpqa2_docids), len(train_docids), len(test_docids), len(dev_docids))

506 287 95 100


In [4]:
srl4orl_docids = train_docids + dev_docids + test_docids

In [5]:
set(mpqa2_docids).issuperset(srl4orl_docids)

True

In [7]:
def base_n(val, base, digits):
    if val > 0:
        digits.append(val%base)
        val = val // base
        base_n(val, base, digits)

def convert_to_base_n(val, base):
    if val == 0:
        return 0
    digits = []
    base_n(val, base, digits)
    return list(reversed(digits))

convert_to_base_n(87, 12)

[7, 3]

In [9]:
def perm(level, m, n, path, allpaths):
    if level == m:
        allpaths.append(path)
    else:
        for i in range(n):
            newpath = copy(path) + [i]
            perm(level + 1, m, n, newpath, allpaths)

allpaths = []
perm(0, 3, 3, [], allpaths)

In [10]:
allpaths

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 1],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [0, 2, 2],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 1, 1],
 [1, 1, 2],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 1, 0],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1],
 [2, 2, 2]]

In [2]:
t = torch.randn((2, 2))

In [3]:
t

tensor([[ 0.0663, -1.0796],
        [ 1.3548, -0.7043]])

In [6]:
t.repeat_interleave(2, dim=0)

tensor([[ 0.0663, -1.0796],
        [ 0.0663, -1.0796],
        [ 1.3548, -0.7043],
        [ 1.3548, -0.7043]])

In [9]:
x = torch.full((2, 3), -np.inf)

In [10]:
torch.isneginf(x)

tensor([[True, True, True],
        [True, True, True]])

In [16]:
a = torch.randn((2, 1))
b = torch.randn((2, 2))

In [17]:
a, b

(tensor([[ 0.3694],
         [-0.3209]]),
 tensor([[ 1.2807, -0.0709],
         [ 1.1462,  0.1452]]))

In [18]:
a + b

tensor([[ 1.6501,  0.2984],
        [ 0.8253, -0.1756]])

In [19]:
z = np.random.randn(2, 3, 4)

In [20]:
z.copy()

array([[[ 0.01216562,  1.50855614,  0.57930131, -0.36735845],
        [-1.32607855,  0.40763862,  1.04598649, -0.26717203],
        [ 0.39994192,  0.71066481, -0.55297391,  0.48488782]],

       [[ 0.64331857, -0.36258601, -2.51173549,  1.30932024],
        [ 0.76419553,  0.418696  ,  0.39135371, -0.14745098],
        [ 2.3234002 ,  0.60814347, -2.07335072, -0.56402561]]])

In [21]:
z.reshape(6, 4)

array([[ 0.01216562,  1.50855614,  0.57930131, -0.36735845],
       [-1.32607855,  0.40763862,  1.04598649, -0.26717203],
       [ 0.39994192,  0.71066481, -0.55297391,  0.48488782],
       [ 0.64331857, -0.36258601, -2.51173549,  1.30932024],
       [ 0.76419553,  0.418696  ,  0.39135371, -0.14745098],
       [ 2.3234002 ,  0.60814347, -2.07335072, -0.56402561]])

In [22]:
encoding = torch.randn((2, 5, 3))

In [23]:
encoding

tensor([[[-0.1992,  0.9159, -1.1039],
         [-0.3144,  1.3942,  0.4294],
         [-0.2407, -0.1034, -0.2558],
         [ 0.4851, -0.2881, -1.7557],
         [ 0.5647,  0.4706,  0.4288]],

        [[-0.5440, -0.3124, -0.6409],
         [ 0.5141, -0.0811, -0.4589],
         [ 0.7985,  1.2476, -0.6412],
         [-0.1808, -0.2774, -0.5746],
         [-0.0854,  1.1791, -1.8555]]])

In [24]:
encoding.repeat_interleave(2, dim=0)

tensor([[[-0.1992,  0.9159, -1.1039],
         [-0.3144,  1.3942,  0.4294],
         [-0.2407, -0.1034, -0.2558],
         [ 0.4851, -0.2881, -1.7557],
         [ 0.5647,  0.4706,  0.4288]],

        [[-0.1992,  0.9159, -1.1039],
         [-0.3144,  1.3942,  0.4294],
         [-0.2407, -0.1034, -0.2558],
         [ 0.4851, -0.2881, -1.7557],
         [ 0.5647,  0.4706,  0.4288]],

        [[-0.5440, -0.3124, -0.6409],
         [ 0.5141, -0.0811, -0.4589],
         [ 0.7985,  1.2476, -0.6412],
         [-0.1808, -0.2774, -0.5746],
         [-0.0854,  1.1791, -1.8555]],

        [[-0.5440, -0.3124, -0.6409],
         [ 0.5141, -0.0811, -0.4589],
         [ 0.7985,  1.2476, -0.6412],
         [-0.1808, -0.2774, -0.5746],
         [-0.0854,  1.1791, -1.8555]]])

In [25]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [26]:
t = torch.zeros((3, 4), dtype=torch.long, device="cuda:0")

In [27]:
t

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], device='cuda:0')

In [28]:
t.dtype

torch.int64

In [29]:
t[1,:3] = [1,2,3]

TypeError: can't assign a list to a torch.cuda.LongTensor

In [30]:
t[1,2] = 5

In [31]:
t

tensor([[0, 0, 0, 0],
        [0, 0, 5, 0],
        [0, 0, 0, 0]], device='cuda:0')